In [4]:
import numpy as np 

In [5]:
np_array= np.array([1,2,4,2,5,3,4,3])
print(np_array)
type(np_array)

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

[1 2 4 2 5 3 4 3]
0
1
2
3


In [6]:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [21]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


6


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [22]:
print(arr.dtype)


int64


In [23]:
dtype_arr = np.array([1,2,3,4,5,6], dtype='i2')

In [24]:
new_type = dtype_arr.astype(dtype='f')
print(new_type.dtype)
print(new_type)
new_type.astype('i')


float32
[1. 2. 3. 4. 5. 6.]


array([1, 2, 3, 4, 5, 6], dtype=int32)

In [25]:
x = new_type.copy()
x[1] = 3
print(new_type)
print(x)

[1. 2. 3. 4. 5. 6.]
[1. 3. 3. 4. 5. 6.]


In [27]:
print(new_type.shape)
print(arr.shape)


(6,)
(2, 2, 3)
