In [82]:
import numpy as np 

In [83]:
np_array= np.array([1,2,4,2,5,3,4,3])
print(np_array)
type(np_array)

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

[1 2 4 2 5 3 4 3]
0
1
2
3


In [84]:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [85]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


6


In [86]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [87]:
print(arr.dtype)


int64


In [88]:
dtype_arr = np.array([1,2,3,4,5,6])

In [89]:
new_type = dtype_arr.astype(dtype='f')
print(new_type.dtype)
print(new_type)
new_type.astype('i')


float32
[1. 2. 3. 4. 5. 6.]


array([1, 2, 3, 4, 5, 6], dtype=int32)

In [90]:
x = new_type.copy()
x[1] = 3
print(new_type)
print(x)

[1. 2. 3. 4. 5. 6.]
[1. 3. 3. 4. 5. 6.]


In [91]:
print(new_type.shape)
print(arr.shape)


(6,)
(7,)


In [92]:
shape_check = np.array(arr,ndmin=4)
print(shape_check.shape)
print(arr.shape)
print(arr)
print(shape_check)

(1, 1, 1, 7)
(7,)
[1 2 3 4 5 6 7]
[[[[1 2 3 4 5 6 7]]]]


In [93]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Before reshaping arr: ",arr.shape)
print(arr)
arr = arr.reshape(4,3).copy() ## Otherwise it would be a view()
print("After reshaping arr: ",arr.shape)
print(arr)


Before reshaping arr:  (12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
After reshaping arr:  (4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


 **-1** indicates that we don't specify the last dimension and it would be calculated automatically

In [94]:
unknown_dimension=arr.reshape(2,3,-1).copy() 
print(unknown_dimension)
print(unknown_dimension.shape)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [95]:
##flatten an array
flat = unknown_dimension.reshape(-1).copy()
print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [96]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)
print("********")
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]
********
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [97]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [98]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [99]:

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [100]:
for index,value in np.ndenumerate(arr=arr):
    print(index,value)

(0,) 1
(1,) 2
(2,) 3


In [105]:
arr1 = np.array([1,6,34,435,7])
arr2 = np.array([1,2,3,4,123])
meow = np.concatenate((arr1,arr2))
print(meow)

[  1   6  34 435   7   1   2   3   4 123]


In [109]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
