In [2]:
import numpy as np 

In [3]:
np_array= np.array([1,2,4,2,5,3,4,3])
print(np_array)
type(np_array)

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

[1 2 4 2 5 3 4 3]
0
1
2
3


In [4]:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [5]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


6


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [7]:
print(arr.dtype)


int64


In [8]:
dtype_arr = np.array([1,2,3,4,5,6])

In [9]:
new_type = dtype_arr.astype(dtype='f')
print(new_type.dtype)
print(new_type)
new_type.astype('i')


float32
[1. 2. 3. 4. 5. 6.]


array([1, 2, 3, 4, 5, 6], dtype=int32)

In [10]:
x = new_type.copy()
x[1] = 3
print(new_type)
print(x)

[1. 2. 3. 4. 5. 6.]
[1. 3. 3. 4. 5. 6.]


In [11]:
print(new_type.shape)
print(arr.shape)


(6,)
(7,)


In [12]:
shape_check = np.array(arr,ndmin=4)
print(shape_check.shape)
print(arr.shape)
print(arr)
print(shape_check)

(1, 1, 1, 7)
(7,)
[1 2 3 4 5 6 7]
[[[[1 2 3 4 5 6 7]]]]


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Before reshaping arr: ",arr.shape)
print(arr)
arr = arr.reshape(4,3).copy() ## Otherwise it would be a view()
print("After reshaping arr: ",arr.shape)
print(arr)


Before reshaping arr:  (12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
After reshaping arr:  (4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


 **-1** indicates that we don't specify the last dimension and it would be calculated automatically

In [14]:
unknown_dimension=arr.reshape(2,3,-1).copy() 
print(unknown_dimension)
print(unknown_dimension.shape)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [15]:
##flatten an array
flat = unknown_dimension.reshape(-1).copy()
print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)
print("********")
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]
********
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [17]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [18]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [19]:

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [20]:
for index,value in np.ndenumerate(arr=arr):
    print(index,value)

(0,) 1
(1,) 2
(2,) 3


In [21]:
arr1 = np.array([1,6,34,435,7])
arr2 = np.array([1,2,3,4,123])
meow = np.concatenate((arr1,arr2))
print(meow)

[  1   6  34 435   7   1   2   3   4 123]


In [22]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [31]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
arr

array([[1, 4],
       [2, 5],
       [3, 6]])

In [34]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [35]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))
arr

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [40]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [42]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [44]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [45]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [50]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
## returns all occurences
print(x)

(array([3, 5, 6]),)


In [51]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [53]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [54]:

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [56]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [57]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [58]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
