In [4]:
import numpy as np 

In [5]:
np_array= np.array([1,2,4,2,5,3,4,3])
print(np_array)
type(np_array)

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

[1 2 4 2 5 3 4 3]
0
1
2
3


In [6]:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [21]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


6


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [22]:
print(arr.dtype)


int64


In [23]:
dtype_arr = np.array([1,2,3,4,5,6], dtype='i2')

In [24]:
new_type = dtype_arr.astype(dtype='f')
print(new_type.dtype)
print(new_type)
new_type.astype('i')


float32
[1. 2. 3. 4. 5. 6.]


array([1, 2, 3, 4, 5, 6], dtype=int32)

In [25]:
x = new_type.copy()
x[1] = 3
print(new_type)
print(x)

[1. 2. 3. 4. 5. 6.]
[1. 3. 3. 4. 5. 6.]


In [27]:
print(new_type.shape)
print(arr.shape)


(6,)
(2, 2, 3)


In [32]:
shape_check = np.array(arr,ndmin=4)
print(shape_check.shape)
print(arr.shape)
print(arr)
print(shape_check)

(1, 2, 2, 3)
(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Before reshaping arr: ",arr.shape)
print(arr)
arr = arr.reshape(4,3).copy() ## Otherwise it would be a view()
print("After reshaping arr: ",arr.shape)
print(arr)


Before reshaping arr:  (12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
After reshaping arr:  (4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


 **-1** indicates that we don't specify the last dimension and it would be calculated automatically

In [43]:
unknown_dimension=arr.reshape(2,3,-1).copy() 
print(unknown_dimension)
print(unknown_dimension.shape)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [44]:
##flatten an array
flat = unknown_dimension.reshape(-1).copy()
print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)
print("********")
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]
********
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
